version: '2'
services:
  mongodb:
    image: tutum/mongodb
    environment:
      - MONGODB_USER=root
      - MONGODB_DATABASE=dmall
      - MONGODB_PASS=mypass
  mariadb:
    image: mariadb:10.0
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
    volumes:
      - ./custom:/etc/mysql/conf.d
    depends_on:
      - mongodb
  web:
    hostname: sjerpnext
    command: /usr/sbin/sshd -D
    image: harrifeng/sjerpnext:sshd
    volumes:
      - hfeng:/home/hfeng
    ports:
      - "2226:22"
      - "8006:8000"
    depends_on:
      - mariadb
volumes:
  hfeng:
    external: true
