version: '2'
services:
  db:
    image: tutum/mongodb
    environment:
      - MONGODB_USER=root
      - MONGODB_DATABASE=dmall
      - MONGODB_PASS=mypass
  web:
    hostname: sjerpnext
    command: /usr/sbin/sshd -D
    image: harrifeng/sjerpnext:hfeng
    volumes:
      - hfeng:/home/hfeng
    ports:
      - "2226:22"
      - "8006:8000"
    depends_on:
      - db
volumes:
  hfeng:
    external: true
