version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - js_data:/var/lib/mysql
  web:
    hostname: jsstudy
    image: harrifeng/js_study:root
    command: /usr/sbin/sshd -D
    volumes:
      - root:/root
    ports:
      - "2225:22"
      - "5000:8000"
      - "5080:8080"
      - "5200:4200"
    depends_on:
      - db
    environment:
      - DB_HOST=db
volumes:
  js_data:
    external: true
  root:
    external: true
