version: '2'
services:
  db:
    image: harrifeng/mariadb:10.1-frappe
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes      
    volumes:
      - ./custom:/etc/mysql/conf.d
  web:
    user: travis
    working_dir: /home/travis
    image: harrifeng/setup_frappe:finish
    volumes:
      - ./frappe_sj:/home/travis/frappe_sj
      - ./custom:/home/travis/custom
    command: /home/travis/custom/prepare.sh
    depends_on:
      - db
    
