version: '2'
services:
  db:
    image: harrifeng/mariadb:10.1-frappe
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./custom:/etc/mysql/conf.d
  web:
    build: .
    depends_on:
      - db
    
