version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - rd_data:/var/lib/mysql
  web:
    image: harrifeng/rails_demo:root
    command: /usr/sbin/sshd -D
    volumes:
      - root:/root
    ports:
      - "2222:22"
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
volumes:
  rd_data:
    external: true
  root:
    external: true
