version: '2'
services:
  db:
    image: mysql:5.6
    hostname: mysql-study
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ms_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  ms_data:
    external: true
