version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ms_data:/var/lib/mysql
  web:
    image: hfeng/mysql_study
    command: /usr/sbin/sshd -D
    volumes:
      - ms_code:/mycode
      - root:/root
    ports:
      - "2223:22"
    depends_on:
      - db
    environment:
      - DB_HOST=db
volumes:
  ms_data:
    external: true
  ms_code:
    external: true
  root:
    external: true
