version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ps_data:/var/lib/mysql
  web:
    image: harrifeng/python3_study:root
    command: /usr/sbin/sshd -D
    volumes:
      - ps_code:/mycode
      - root:/root
    ports:
      - "2224:22"
      - "7000:7000"
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
volumes:
  ps_data:
    external: true
  ps_code:
    external: true
  root:
    external: true
