version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ps_data:/var/lib/mysql
  web:
    image: harrifeng/python3_study
    command: /usr/sbin/sshd -D
    volumes:
      - ps_code:/mycode
      - root:/root
    ports:
      - "2224:22"
    depends_on:
      - db
    environment:
      - DB_HOST=db
volumes:
  ps_data:
    external: true
  ps_code:
    external: true
  root:
    external: true
